#include "argus_mpc/QuadrotorMpc.hpp"

extern "C" {
#include "acados_c/ocp_nlp_interface.h"
#include "acados_solver_quadrotor.h"
}
// Auto-generated by scripts/generate_mpc.py — source of truth is config/quadrotor.yaml.
#include "argus_params.h"

#include <array>
#include <stdexcept>
#include <string>

namespace argus_mpc {

namespace {
constexpr int kN   = QUADROTOR_N;
constexpr int kNx  = QUADROTOR_NX;
constexpr int kNu  = QUADROTOR_NU;
constexpr int kNy  = QUADROTOR_NY;
constexpr int kNyN = QUADROTOR_NYN;
constexpr int kNp  = QUADROTOR_NP;

// If the generated model's dimensions ever change, this fails the build
// loudly instead of silently mis-packing state/yref arrays below.
static_assert(kNx == 12, "State/step() packing assumes NX == 12 ([x,y,z,vx,vy,vz,phi,theta,psi,p,q,r])");
static_assert(kNu == 4,  "Command/step() packing assumes NU == 4 ([T,p_cmd,q_cmd,r_cmd])");
static_assert(kNy == 13, "step() yref packing assumes NY == 13 ([x,y,z,vx,vy,vz,phi,theta,r_fov,T,p_cmd,q_cmd,r_cmd])");
static_assert(kNyN == 9, "step() terminal yref packing assumes NYN == 9 ([x,y,z,vx,vy,vz,phi,theta,r_fov])");
static_assert(kNp == 3,  "step() parameter packing assumes NP == 3 ([p_target_x, p_target_y, p_target_z]); run generate_mpc.py");

using RawState = std::array<double, kNx>;
using RawInput = std::array<double, kNu>;
}  // namespace

struct QuadrotorMpc::Impl
{
    quadrotor_solver_capsule* capsule;
    ocp_nlp_config*           config;
    ocp_nlp_dims*             dims;
    ocp_nlp_in*               nlp_in;
    ocp_nlp_out*              nlp_out;
    bool                      warm_started = false;

    Impl()
    {
        capsule = quadrotor_acados_create_capsule();
        const int status = quadrotor_acados_create(capsule);
        if (status != 0)
            throw std::runtime_error(
                "quadrotor_acados_create() failed with status " + std::to_string(status));

        config  = quadrotor_acados_get_nlp_config(capsule);
        dims    = quadrotor_acados_get_nlp_dims(capsule);
        nlp_in  = quadrotor_acados_get_nlp_in(capsule);
        nlp_out = quadrotor_acados_get_nlp_out(capsule);
    }

    ~Impl()
    {
        quadrotor_acados_free(capsule);
        quadrotor_acados_free_capsule(capsule);
    }
};

QuadrotorMpc::QuadrotorMpc() : impl_(std::make_unique<Impl>()) {}
QuadrotorMpc::~QuadrotorMpc() = default;

int QuadrotorMpc::horizonLength() const { return kN; }

Command QuadrotorMpc::step(const State& x0, const std::vector<Reference>& horizon,
                           const TargetState& target)
{
    if (static_cast<int>(horizon.size()) != kN)
        throw std::invalid_argument(
            "QuadrotorMpc::step(): horizon.size() must equal horizonLength() (" +
            std::to_string(kN) + ")");

    Impl& impl = *impl_;

    const RawState x0_raw = {
        x0.x,   x0.y,     x0.z,
        x0.vx,  x0.vy,    x0.vz,
        x0.phi, x0.theta, x0.psi,
        x0.p,   x0.q,     x0.r,
    };

    // First call: warm-start every stage at the current state / hover thrust.
    if (!impl.warm_started) {
        const RawInput u_init = {ARGUS_T_HOVER, 0.0, 0.0, 0.0};
        for (int i = 0; i <= kN; ++i)
            ocp_nlp_out_set(impl.config, impl.dims, impl.nlp_out, impl.nlp_in, i, "x",
                             const_cast<double*>(x0_raw.data()));
        for (int i = 0; i < kN; ++i)
            ocp_nlp_out_set(impl.config, impl.dims, impl.nlp_out, impl.nlp_in, i, "u",
                             const_cast<double*>(u_init.data()));
        impl.warm_started = true;
    }

    // ── Inject target position into model.p for every stage ─────────────────
    double p_target[kNp] = {target.x, target.y, target.z};
    for (int i = 0; i <= kN; ++i)
        quadrotor_acados_update_params(impl.capsule, i, p_target, kNp);

    // ── Pin the measured state as the initial-stage equality constraint ─────
    ocp_nlp_constraints_model_set(impl.config, impl.dims, impl.nlp_in, impl.nlp_out, 0, "lbx",
                                   const_cast<double*>(x0_raw.data()));
    ocp_nlp_constraints_model_set(impl.config, impl.dims, impl.nlp_in, impl.nlp_out, 0, "ubx",
                                   const_cast<double*>(x0_raw.data()));

    // ── Per-stage horizon reference ───────────────────────────────────────────
    // yref layout: [x,y,z, vx,vy,vz, phi,theta, r_fov, T, p_cmd,q_cmd,r_cmd]
    // Velocity yref is the target's velocity — incentivises the drone to match speed.
    for (int j = 0; j < kN; ++j) {
        const Reference& ref = horizon[j];
        double yref[kNy] = {
            ref.x,      ref.y,      ref.z,
            target.vx,  target.vy,  target.vz,
            0.0, 0.0,             // phi, theta reference: level
            0.0,                  // r_fov reference: target inside the FOV cone
            ARGUS_T_HOVER, 0.0, 0.0, 0.0,
        };
        ocp_nlp_cost_model_set(impl.config, impl.dims, impl.nlp_in, j, "yref", yref);
    }
    {
        const Reference& ref = horizon[kN - 1];
        double yref_e[kNyN] = {
            ref.x,     ref.y,     ref.z,
            target.vx, target.vy, target.vz,
            0.0, 0.0,
            0.0,
        };
        ocp_nlp_cost_model_set(impl.config, impl.dims, impl.nlp_in, kN, "yref", yref_e);
    }

    // ── Solve (SQP-RTI: one iteration per call) ──────────────────────────────
    const int status = quadrotor_acados_solve(impl.capsule);

    RawInput u{};
    ocp_nlp_out_get(impl.config, impl.dims, impl.nlp_out, 0, "u", u.data());

    // ── Shift warm-start: stage i+1 → stage i ────────────────────────────────
    RawState x_s{};
    RawInput u_s{};
    for (int i = 0; i < kN - 1; ++i) {
        ocp_nlp_out_get(impl.config, impl.dims, impl.nlp_out, i + 1, "x", x_s.data());
        ocp_nlp_out_get(impl.config, impl.dims, impl.nlp_out, i + 1, "u", u_s.data());
        ocp_nlp_out_set(impl.config, impl.dims, impl.nlp_out, impl.nlp_in, i, "x", x_s.data());
        ocp_nlp_out_set(impl.config, impl.dims, impl.nlp_out, impl.nlp_in, i, "u", u_s.data());
    }
    ocp_nlp_out_get(impl.config, impl.dims, impl.nlp_out, kN, "x", x_s.data());
    ocp_nlp_out_set(impl.config, impl.dims, impl.nlp_out, impl.nlp_in, kN, "x", x_s.data());

    // argus u layout: [T, p_cmd, q_cmd, r_cmd] — T in Newtons, Command wants
    // thrust normalised to hover (1.0 == hover).
    return Command{
        u[0] / ARGUS_T_HOVER,
        u[1],
        u[2],
        u[3],
        status,
    };
}

}  // namespace argus_mpc
